### ISSUE TITLE
Request and headers are missing 

### ISSUE THREAD

**Issue by anilmagzter** [tessellator/sveltekit-adapter-lambda#1]
Not able to retrieve headers and request from the server webhooks. request param is empty as below

{
    "cookies": {},
    "locals": {},
    "params": {
        "home": ""
    },
    "request": {},
    "route": {
        "id": "/[...home=empty]"
    },
    "url": "https://server.com/",
    "isDataRequest": false
}

**Comment by tessellator** [comment]
Hey @anilmagzter - thanks for reporting your issue! It looks like you have already closed it. Did you get your issue resolved?
